version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: quiz_app_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql &&
        a2enmod rewrite &&
        apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: quiz_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_app
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./quiz_app.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sample_questions.sql:/docker-entrypoint-initdb.d/02_data.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quiz_app_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
